// Lazy-loaded PDF export. jsPDF + html2canvas are heavy (~200 KB),
// so we import them dynamically only when the user actually taps Export.

type ExportMsg = { role: "user" | "assistant"; content: string; createdAt?: string };

export async function exportChatAsPdf(
  sessionTitle: string,
  farmerName: string,
  messages: ExportMsg[]
): Promise<void> {
  if (messages.length === 0) {
    throw new Error("Nothing to export yet");
  }

  const [{ jsPDF }, html2canvasMod] = await Promise.all([
    import("jspdf"),
    import("html2canvas"),
  ]);
  const html2canvas = html2canvasMod.default;

  // Build an off-screen printable version of the chat with print-friendly styling.
  const container = document.createElement("div");
  container.style.cssText = [
    "position:fixed",
    "left:-10000px",
    "top:0",
    "width:640px",
    "background:#ffffff",
    "color:#1a1f16",
    "font-family: 'Inter', 'Noto Sans Devanagari', system-ui, sans-serif",
    "padding:32px",
    "font-size:14px",
    "line-height:1.55",
  ].join(";");

  const stamp = new Date().toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });

  container.innerHTML = `
    <div style="border-bottom:2px solid #2e7d32;padding-bottom:12px;margin-bottom:20px;">
      <div style="font-size:22px;font-weight:700;color:#2e7d32;">🌾 KrishiMitra</div>
      <div style="font-size:12px;color:#6b7566;margin-top:4px;">
        Chat: <b>${escapeHtml(sessionTitle)}</b> · Farmer: ${escapeHtml(farmerName)} · Exported ${stamp}
      </div>
    </div>
    ${messages
      .map((m) => {
        const isUser = m.role === "user";
        return `
        <div style="margin-bottom:14px;">
          <div style="font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;color:${isUser ? "#2e7d32" : "#6b7566"};margin-bottom:4px;">
            ${isUser ? farmerName : "KrishiMitra AI"}
          </div>
          <div style="background:${isUser ? "#eef7ee" : "#fbf7ec"};border:1px solid ${isUser ? "#2e7d3220" : "#e6e2d3"};border-radius:10px;padding:10px 14px;white-space:pre-wrap;word-wrap:break-word;">
            ${escapeHtml(m.content)}
          </div>
        </div>`;
      })
      .join("")}
    <div style="margin-top:24px;padding-top:12px;border-top:1px solid #e6e2d3;font-size:10px;color:#6b7566;text-align:center;">
      Generated by KrishiMitra · ${messages.length} messages
    </div>
  `;
  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      backgroundColor: "#ffffff",
      logging: false,
      useCORS: true,
    });
    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF({ orientation: "portrait", unit: "px", format: "a4" });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pageWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    // Slice the tall canvas image across multiple A4 pages
    let heightLeft = imgHeight;
    let position = 0;
    pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
    while (heightLeft > 0) {
      position -= pageHeight;
      pdf.addPage();
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    const filename = `KrishiMitra_${slug(sessionTitle)}_${new Date()
      .toISOString()
      .slice(0, 10)}.pdf`;
    pdf.save(filename);
  } finally {
    document.body.removeChild(container);
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 40) || "chat";
}
